# 
# Docker compose file for TANGO database, database device server and tango test ds
# the containers are based on images on gerhardlr docker repository (to be moved later)
# the composition connects to an externally defined network: docker network create $DOCKER_NETWORK
# check that you have the same external network attched to your home grown containers if you want to use these services
# 
#
version: '3'
volumes:
  tangodb: {}
        
services:
  tangodb:
    build: .
    container_name: tangodb_test   
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango


